### PR TITLE
Fix hang in hip custom scan with warp size 32

### LINKED ISSUE #518: Basic_INDEXLIST and Algorithm_SCAN hang the GPU on Radeon 7900 XTX
**Describe the bug**

On RHEL10 with the ROCm packages from
https://copr.fedorainfracloud.org/coprs/g/rocm-packagers-sig/cs10-mathlib-preview/ installed running on a Radeon 7900 XTX two of the tests seem to hang the GPU:  Algorithm_SCAN and Basic_INDEXLIST all 73 of the other tests run to completion. 

This COPR repo is built and maintained by the AMD engineer who maintains the fedora ROCm packages and this COPR repo is intended to be a prototype repository for future integration into RHEL.

The kernel version is: 6.12.0-55.13.1.el10_0.x86_64 using the inbox amdgpu driver
lspci says it is a C8 version of the Navi 31
43:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M] (rev c8) (prog-if 00 [VGA controller])
and fmupdmgr says that the firmware version is:
                               "Version" : "022.001.002.009.000001",
                               "VersionFormat" : "plain",
                               "VersionRaw" : 369164809,

Doing a little debugging doesn't show anything obvious:

(gdb) bt
#0  0x00007ffff62bde9c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff6267a96 in raise () from /lib64/libc.so.6
#2  0x00007ffff624f8fa in abort () from /lib64/libc.so.6
#3  0x00007ffff5e2b6bb in rocr::core::Runtime::HwExceptionHandler (val=<optimized out>, arg=<optimized out>) at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/runtime.cpp:1820
#4  0x00007ffff5e970aa in operator() (__closure=0x7ffff59fe420, index=2, value=<optimized out>, wait_any=true) at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/runtime.cpp:1551
#5  rocr::core::Runtime::AsyncEventsLoop (_eventsInfo=0x555556ddabc0) at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/runtime.cpp:1633
#6  0x00007ffff5e345a1 in rocr::os::ThreadTrampoline (arg=<optimized out>) at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/util/lnx/os_linux.cpp:86
#7  0x00007ffff62bc11a in start_thread () from /lib64/libc.so.6
#8  0x00007ffff632cc3c in clone3 () from /lib64/libc.so.6
(gdb) info threads
  Id   Target Id                                          Frame
  1    Thread 0x7ffff7f64140 (LWP 774433) "raja-perf.exe" 0x00007ffff5e7e3e9 in rocr::__rdtsc () at /usr/lib/gcc/x86_64-redhat-linux/14/include/ia32intrin.h:114
* 2    Thread 0x7ffff59ff6c0 (LWP 774436) "raja-perf.exe" 0x00007ffff62bde9c in __pthread_kill_implementation () from /lib64/libc.so.6
  4    Thread 0x7ffee3bff6c0 (LWP 774438) "raja-perf.exe" 0x00007ffff63285ff in ioctl () from /lib64/libc.so.6
  6    Thread 0x7ffff5c7d6c0 (LWP 774442) "raja-perf.exe" 0x00007ffff63285ff in ioctl () from /lib64/libc.so.6
(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff7f64140 (LWP 774433))]
#0  0x00007ffff5e7e3e9 in rocr::__rdtsc () at /usr/lib/gcc/x86_64-redhat-linux/14/include/ia32intrin.h:114
114      return __builtin_ia32_rdtsc ();
(gdb) bt
#0  0x00007ffff5e7e3e9 in rocr::__rdtsc () at /usr/lib/gcc/x86_64-redhat-linux/14/include/ia32intrin.h:114
#1  rocr::timer::fast_clock::raw_now () at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/util/timer.h:149
#2  rocr::timer::fast_clock::now () at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/util/timer.h:140
#3  rocr::core::InterruptSignal::WaitRelaxed (this=0x555557c2b720, condition=HSA_SIGNAL_CONDITION_LT, compare_value=1, timeout=<optimized out>, wait_hint=HSA_WAIT_STATE_ACTIVE)
    at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/interrupt_signal.cpp:166
#4  0x00007ffff5e78dde in rocr::core::InterruptSignal::WaitAcquire (this=<optimized out>, condition=<optimized out>, compare_value=<optimized out>, timeout=<optimized out>, wait_hint=<optimized out>)
    at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/interrupt_signal.cpp:205
#5  0x00007ffff5e6e5ca in rocr::HSA::hsa_signal_wait_scacquire (hsa_signal=..., condition=<optimized out>, compare_value=<optimized out>, timeout_hint=<optimized out>, wait_state_hint=<optimized out>)
    at /usr/src/debug/rocm-runtime-6.4.1-1.el10.x86_64/runtime/hsa-runtime/core/runtime/hsa.cpp:1249
#6  0x00007ffff6c39d98 in amd::roc::WaitForSignal (signal=..., active_wait=<optimized out>) at /usr/src/debug/rocclr-6.4.1-1.el10.x86_64/rocclr/device/rocm/rocvirtual.hpp:60
#7  0x00007ffff6c1fc42 in amd::HostQueue::finish (this=0x5555571f1600, cpu_wait=<optimized out>) at /usr/src/debug/rocclr-6.4.1-1.el10.x86_64/rocclr/platform/commandqueue.cpp:165
#8  0x00007ffff6b377e3 in hip::hipStreamSynchronize_common (stream=<optimized out>) at /usr/src/debug/rocclr-6.4.1-1.el10.x86_64/hipamd/src/hip_stream.cpp:373
#9  0x00007ffff6b38161 in hip::hipStreamSynchronize (stream=0x5555571f1600) at /usr/src/debug/rocclr-6.4.1-1.el10.x86_64/hipamd/src/hip_stream.cpp:383
#10 0x000055555561a49d in rajaperf::basic::INDEXLIST::runHipVariantImpl<256ul, 15ul> (this=0x555556d911e0, vid=<optimized out>) at /home/ben/Work/RAJAPerf/src/basic/INDEXLIST-Hip.cpp:117
#11 0x00005555555c4955 in rajaperf::KernelBase::execute (this=0x555556d911e0, vid=rajaperf::Base_HIP, tune_idx=0) at /home/ben/Work/RAJAPerf/src/common/KernelBase.cpp:370
#12 0x00005555555bac49 in rajaperf::Executor::runKernel (this=this@entry=0x7fffffffd5d8, kernel=0x555556d911e0, print_kernel_name=<optimized out>) at /home/ben/Work/RAJAPerf/src/common/Executor.cpp:713
#13 0x00005555555ba5ae in rajaperf::Executor::runSuite (this=0x7fffffffd5d8) at /home/ben/Work/RAJAPerf/src/common/Executor.cpp:666
#14 0x00005555555b7650 in main (argc=<optimized out>, argv=<optimized out>) at /home/ben/Work/RAJAPerf/src/RAJAPerfSuiteDriver.cpp:59

**To Reproduce**

git clone https://github.com/LLNL/RAJAPerf
cd RAJAPerf; mkdir build-hip; cd build-hip
cmake -DENABLE_HIP=On -DCMAKE_BUILD_TYPE=Debug -DCMAKE_HIP_ARCHITECTURES="gfx1100" ..
make -j VERBOSE=1
bin/raja-perf.exe --show-progress -k Algorithm_SCAN       # or Basic_INDEXLIST

Note that my workstation machine has both a Radeon Pro VII gfx906 and a Radeon 7900 XTX gfx1100 in it. 

1) To just enable the 7900 I did:
export ROCR_VISIBLE_DEVICES=GPU-32718d9ad8c12635

2) However cmake still picked up the gfx906 and was passing it as the target GPU architecture. That is why I explictly passed -DCMAKE_HIP_ARCHITECTURES="gfx1100" on the cmake line. 

**Expected behavior**

It should run to completion.

**Compilers & Libraries (please complete the following information):**
rocm-runtime-6.4.1-1.el10.x86_64
rocminfo-6.4.0-1.el10.x86_64
rocm-llvm-filesystem-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-libc++-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-libs-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-libs-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-libc++-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-runtime-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-static-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-lld-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-device-libs-19-9.rocm6.4.1.el10~bootstrap.x86_64
hipcc-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-comgr-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-comgr-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-hip-6.4.1-1.el10.x86_64
rocm-runtime-devel-6.4.1-1.el10.x86_64
rocm-hip-devel-6.4.1-1.el10.x86_64
rocminfo-debugsource-6.4.0-1.el10.x86_64
rocminfo-debuginfo-6.4.0-1.el10.x86_64
rocm-omp-6.4.0-1.el10.x86_64
rocm-omp-devel-6.4.0-1.el10.x86_64
rocm-omp-debugsource-6.4.0-1.el10.x86_64
rocm-omp-devel-debuginfo-6.4.0-1.el10.x86_64
rocm-clang-tools-extra-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-tools-extra-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-cmake-6.4.0-1.el10.noarch
rocm-hip-debuginfo-6.4.1-1.el10.x86_64
rocm-rpm-macros-6.2.2-4.el10.x86_64
rocm-smi-6.4.1-1.el10.x86_64
rocm-smi-devel-6.4.1-1.el10.x86_64
rocm-rpm-macros-modules-6.2.2-4.el10.x86_64
rocm-omp-static-6.4.0-1.el10.x86_64
rocm-libc++-static-19-9.rocm6.4.1.el10~bootstrap.x86_64
hipcc-libomp-devel-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-compilersupport-debugsource-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-runtime-debugsource-6.4.1-1.el10.x86_64
rocm-runtime-debuginfo-6.4.1-1.el10.x86_64
rocm-smi-debugsource-6.4.1-1.el10.x86_64
rocm-smi-debuginfo-6.4.1-1.el10.x86_64
hipcc-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-clang-libs-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-comgr-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-libc++-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-lld-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-devel-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64
rocm-llvm-libs-debuginfo-19-9.rocm6.4.1.el10~bootstrap.x86_64

**Additional context**

Part of the purpose of this test is to ensure that the ROCm packages which are derived from the ones being made for Fedora run acceptably on RHEL10. Something nice is that these packages include debug information for at least the CPU code. (I haven't looked yet to see if they include DWARF for the GPUs yet and I haven't started running rocm-gdb -- that is future testing.)

This very well could be a problem with ROCm 6.4.1 on the Radeon 7900 XTX. If that is likely the case, then please let me know and I will work with AMD to debug it.

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary

Fix hang in hip custom scan implementation with warp size 32, on consumer cards.
Add a command line option to enable custom scan tunings, default to on.

- This PR is a (refactoring, bugfix, feature, something else)
- It does the following (modify list as needed):
  - Fixes #518

### CODE REVIEW

File: src/common/HipGridScan.hpp [hunk 1]
```diff
@@ -101,99 +104,135 @@ struct GridScan
...
 
-          if (!last_block) {
-            grid_counts[block_id] = prev_grid_count + inclusive[items_per_thread-1];   // write inclusive scan result for grid through block
-            __threadfence();                        // ensure grid_counts ready (release)
-            atomicExch(&block_readys[block_id], 2u); // write grid_counts is ready
-          }
+      // ensure previous block_counts are ready
+      // this checks that block counts is ready for all blocks above
+      // the highest grid count that is ready
+      while (~prev_blocks_ready_ballot >= prev_grids_ready_ballot) {
```
Comment (MrBurmark) [inline src/common/HipGridScan.hpp:198]: This was always false leading to a hang. The most significant bits of the numbers returned from ballot were always 0 when the warp size was 32 but the numbers were 64-bit.

File: src/algorithm/SCAN-Cuda.cpp [hunk 2]
```diff
@@ -33,7 +33,7 @@ using cuda_items_per_thread_type = integer::make_gpu_items_per_thread_list_type<
 
 template < size_t block_size, size_t items_per_thread >
 __launch_bounds__(block_size)
-__global__ void scan(Real_ptr x,
+__global__ void scan_custom(Real_ptr x,
                      Real_ptr y,
```
Comment (adayton1) [inline src/algorithm/SCAN-Cuda.cpp]: Could you fix the whitespace alignment for these args?

File: src/common/RunParams.hpp [hunk 3]
```diff
@@ -318,6 +320,8 @@ class RunParams {
   Index_type halo_width; /*!< halo width used in halo kernels (input option) */
   Index_type halo_num_vars; /*!< num vars used in halo kernels (input option) */
 
+  bool enable_custom_scan;
```
Comment (adayton1) [inline src/common/RunParams.hpp]: Can you document this variable?

File: src/common/CudaGridScan.hpp [hunk 4]
```diff
@@ -97,99 +94,127 @@ struct GridScan
...
 
-        unsigned prev_block_ready = 0u;
-        unsigned prev_blocks_ready_ballot = 0u;
-        unsigned prev_grids_ready_ballot = 0u;
-
-        // accumulate full warp worths of block counts
-        // stop if run out of full warps of a grid count is ready
-        while (prev_block_base_id >= 0) {
+      for (size_t ti = 0; ti < items_per_thread; ++ti) {
+        exclusive[ti] = prev_grid_count + exclusive[ti];
```
Comment (adayton1) [inline src/common/CudaGridScan.hpp:103]: `+=` would be shorter and make it clear that you are summing into exclusive and inclusive. But whatever you prefer.

Comment (MrBurmark) [reply src/common/CudaGridScan.hpp:103]: I believe I wrote this this way to consistently order the arguments of the operations, despite things being commutative in this case.

**Comment by woodard** [comment]
I can confirm feature/burmark1/custom_scan_flag which is up through commit 1f07bf8d  Document enable_custom_scan fixes the problem on my 7900 XTX

**Review by adayton1 — APPROVED** [review]
